Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2021-02, with the labels that each got.

#46 release create-vm v0.0.4 and execute-in-vm v0.0.3 images
  configs/cleanup-vm.yaml
  configs/create-vm-from-manifest.yaml
  configs/create-vm-from-template.yaml
  configs/execute-in-vm.yaml
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
Labels: approved, dco-signoff: yes, size/S

#48 add better READMEs
  README.md
  tasks/cleanup-vm/README.md
  tasks/create-datavolume-from-manifest/README.md
  tasks/create-vm-from-manifest/README.md
  tasks/create-vm-from-template/README.md
  tasks/execute-in-vm/README.md
  tasks/execute-in-vm/examples/taskruns/execute-in-vm-with-ssh-taskrun.yaml
  templates/create-datavolume-from-manifest/readmes/README.md
  templates/create-vm-from-manifest/readmes/README.md
  templates/create-vm-from-template/readmes/README.md
  templates/execute-in-vm/examples/execute-in-vm-taskrun.yaml
  templates/execute-in-vm/readmes/README.md
Labels: approved, dco-signoff: yes, size/M

#24 add repo-tester pipeline example
  README.md
  examples/pipelines/unit-tester/README.md
  examples/pipelines/unit-tester/unit-tester-pipeline-run.yaml
  examples/pipelines/unit-tester/unit-tester-pipeline.yaml
  modules/execute-in-vm/pkg/utils/parse/clioptions_test.go
  tasks/create-vm-from-template/README.md
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  templates/create-vm-from-manifest/manifests/create-vm.yaml
Labels: approved, dco-signoff: yes, size/L

#49 README: improve English style, add motivation
  README.md
Labels: dco-signoff: yes, size/S

#54 add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, size/M

#55 add generate-ssh-keys stub for CI
  configs/generate-ssh-keys.yaml
  modules/generate-ssh-keys/build/generate-ssh-keys/Dockerfile
  scripts/common.sh
Labels: approved, dco-signoff: yes, size/XS

#53 update docs
  CONTRIBUTING.md
  docs/onboarding-new-task.md
  examples/pipelines/unit-tester/README.md
  examples/pipelines/unit-tester/unit-tester-pipeline.yaml
  examples/pipelines/unit-tester/unit-tester-pipelinerun.yaml
  tasks/create-vm-from-template/README.md
  templates/create-vm-from-template/readmes/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#56 fix unit tester README
  examples/pipelines/unit-tester/README.md
Labels: approved, dco-signoff: yes, size/XS

#57 update unit tester pipeline with generate-ssh-keys task
  README.md
  examples/pipelines/unit-tester/README.md
  examples/pipelines/unit-tester/unit-tester-pipeline.yaml
  examples/pipelines/unit-tester/unit-tester-pipelinerun.yaml
Labels: approved, dco-signoff: yes, size/M

#58 fix #21: handle missing last newlines in private keys in execute-in-vm
  modules/create-vm/vendor/github.com/kubevirt/kubevirt-tekton-tasks/modules/sharedtest/testconstants/ssh.go
  modules/execute-in-vm/pkg/execattributes/ssh-attributes.go
  modules/execute-in-vm/pkg/execattributes/ssh-attributes_test.go
  modules/execute-in-vm/vendor/github.com/kubevirt/kubevirt-tekton-tasks/modules/sharedtest/testconstants/ssh.go
  modules/sharedtest/testconstants/ssh.go
  modules/tests/test/execute_and_cleanup_vm_test.go
  modules/tests/vendor/github.com/kubevirt/kubevirt-tekton-tasks/modules/sharedtest/testconstants/ssh.go
Labels: approved, dco-signoff: yes, size/L
