Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2021-05, with the labels that each got.

#88 update OWNERS
  OWNERS
Labels: dco-signoff: yes, size/XS

#89 fix CI versions of kubevirt and common-templates
  automation/e2e-deploy-resources.sh
  modules/tests/test/wait_for_vmi_status_test.go
Labels: approved, dco-signoff: yes, size/XS

#91 replaced kubevirt config map by patching kubevirt CR
  automation/e2e-deploy-resources.sh
Labels: dco-signoff: yes, lgtm, size/S

#92 add github templates for new PR and new issue
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, size/M
