Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2022-05, with the labels that each got.

#131 add packages golang, git, which to a builder dockerfile
  automation/generatetasks/build/Dockerfile
Labels: dco-signoff: yes, size/XS, lgtm

#132 update owners file
  OWNERS
Labels: dco-signoff: yes, size/XS, lgtm

#129 fix getting of kubevirt components latest release
  automation/e2e-deploy-resources.sh
Labels: dco-signoff: yes, size/M, approved

#134 add gcc package into openshift ci builder image
  automation/generatetasks/build/Dockerfile
Labels: dco-signoff: yes, size/XS, approved, lgtm

#135 create tekton-pipelines namespace during tests
  automation/e2e-deploy-resources.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm

#136 remove tests which doesn't have serviceAccount
  modules/tests/test/copy_template_test.go
  modules/tests/test/create_datavolume_test.go
  modules/tests/test/create_vm_from_manifest_test.go
  modules/tests/test/create_vm_from_template_test.go
  modules/tests/test/execute_and_cleanup_vm_test.go
  modules/tests/test/generate_ssh_keys_test.go
  modules/tests/test/modify-vm-template_test.go
  modules/tests/test/wait_for_vmi_status_test.go
Labels: dco-signoff: yes, size/M, approved, lgtm

#133 add RunStrategy parameter to create vm tasks
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  modules/create-vm/cmd/create-vm/main.go
  modules/create-vm/pkg/utils/parse/clioptions.go
  modules/create-vm/pkg/utils/parse/clioptions_test.go
  modules/create-vm/pkg/vmcreator/vm-creator.go
  modules/tests/test/constants/create-vm.go
  modules/tests/test/create_vm_from_manifest_test.go
  modules/tests/test/create_vm_from_template_test.go
  modules/tests/test/testconfigs/vm-test-config.go
  tasks/create-vm-from-manifest/README.md
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/README.md
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  templates/create-vm-from-manifest/manifests/create-vm.yaml
Labels: dco-signoff: yes, size/L, approved, lgtm

#138 modify-vm-template: Fix updating template labels and annotations
  modules/modify-vm-template/pkg/templates/template-provider.go
  modules/tests/test/constants/modify-vm-template.go
  modules/tests/test/modify-vm-template_test.go
  modules/tests/test/testconfigs/modify-vm-template-test-config.go
Labels: dco-signoff: yes, size/M, lgtm

#121 bump golang version to 1.18
  modules/copy-template/build/copy-template/Dockerfile
  modules/copy-template/go.mod
  modules/copy-template/go.sum
  modules/copy-template/vendor/modules.txt
  modules/create-vm/build/create-vm/Dockerfile
  modules/create-vm/vendor/modules.txt
  modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
  modules/disk-virt-customize/go.mod
  modules/disk-virt-customize/go.sum
  modules/disk-virt-customize/vendor/modules.txt
  modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
  modules/disk-virt-sysprep/go.mod
  modules/disk-virt-sysprep/go.sum
  modules/disk-virt-sysprep/vendor/modules.txt
  modules/execute-in-vm/build/execute-in-vm/Dockerfile
  modules/execute-in-vm/go.mod
  modules/execute-in-vm/go.sum
  modules/execute-in-vm/vendor/modules.txt
  modules/generate-ssh-keys/build/generate-ssh-keys/Dockerfile
  modules/generate-ssh-keys/go.mod
  modules/generate-ssh-keys/go.sum
  modules/generate-ssh-keys/vendor/modules.txt
  modules/modify-vm-template/build/modify-vm-template/Dockerfile
  modules/modify-vm-template/go.mod
  modules/modify-vm-template/go.sum
  modules/modify-vm-template/vendor/modules.txt
  modules/shared/go.mod
  modules/shared/go.sum
  modules/shared/vendor/modules.txt
  modules/sharedtest/go.mod
  modules/sharedtest/go.sum
  modules/tests/go.mod
  modules/tests/go.sum
  modules/tests/vendor/modules.txt
  modules/wait-for-vmi-status/build/wait-for-vmi-status/Dockerfile
  modules/wait-for-vmi-status/go.mod
  modules/wait-for-vmi-status/go.sum
  modules/wait-for-vmi-status/vendor/modules.txt
Labels: dco-signoff: yes, size/L, approved, lgtm

#140 Allow create-datavolume-from-manifest-role to create pods
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  tasks/create-datavolume-from-manifest/manifests/create-datavolume-from-manifest.yaml
  templates/create-datavolume-from-manifest/manifests/create-datavolume-from-manifest-role.yaml
Labels: dco-signoff: yes, size/S, lgtm

#141 bump origin-cli version image to 4.11
  configs/create-datavolume-from-manifest.yaml
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  tasks/create-datavolume-from-manifest/manifests/create-datavolume-from-manifest.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm

#142 Update tekton tasks manifests to version v0.9.1
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm

#144 remove all common-template labels / annotations in copy task
  modules/copy-template/pkg/templates/common-templates.go
  modules/copy-template/pkg/templates/template-provider.go
  modules/copy-template/pkg/templates/template-provider_test.go
Labels: dco-signoff: yes, size/L, approved, lgtm

#145 Update tekton tasks manifests to version v0.9.2
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M, approved

#148 Update examples documentation
  README.md
  examples/pipelines/windows-installer/README.md
  examples/pipelines/windows-installer/windows-installer-pipeline.yaml
  examples/pipelines/windows-installer/windows-installer-pipelinerun.yaml
  examples/pipelines/windows10-customize/README.md
  examples/pipelines/windows10-installer/README.md
Labels: dco-signoff: yes, size/XL, approved, lgtm
