Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2022-06, with the labels that each got.

#151 modify-vm-template: Add deleteTemplate parameter
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  modules/modify-vm-template/pkg/templates/template-provider.go
  modules/modify-vm-template/pkg/utils/parse/clioptions.go
  modules/modify-vm-template/pkg/utils/parse/clioptions_test.go
  modules/tests/test/constants/modify-vm-template.go
  modules/tests/test/modify-vm-template_test.go
  modules/tests/test/testconfigs/modify-vm-template-test-config.go
  tasks/modify-vm-template/README.md
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  templates/modify-vm-template/manifests/modify-vm-template-role.yaml
  templates/modify-vm-template/manifests/modify-vm-template.yaml
Labels: dco-signoff: yes, size/L

#155 [release-v0.9.0] enable creating datasources in create-datavolume-task
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  modules/tests/test/create_datasource_test.go
  modules/tests/test/create_datavolume_test.go
  modules/tests/test/ds/conditions.go
  modules/tests/test/ds/datasource.go
  modules/tests/test/ds/operations.go
  modules/tests/test/testconfigs/dv-ds-test-config.go
  tasks/create-datavolume-from-manifest/manifests/create-datavolume-from-manifest.yaml
  templates/create-datavolume-from-manifest/create-datavolume-script.sh
  templates/create-datavolume-from-manifest/manifests/create-datavolume-from-manifest-role.yaml
Labels: dco-signoff: yes, size/L, approved, lgtm

#152 Onboard create-data-object task
  configs/create-data-object.yaml
  modules/create-data-object/build/create-data-object/Dockerfile
  scripts/common.sh
Labels: dco-signoff: yes, size/S, approved

#162 Bump create-data-object golang version to 1.17 temporarily
  modules/create-data-object/build/create-data-object/Dockerfile
Labels: dco-signoff: yes, size/XS

#164 Add script to obtain Windows 10 ISO download URL in an automated way
  examples/pipelines/windows10-installer/README.md
  examples/pipelines/windows10-installer/getisourl.py
Labels: dco-signoff: yes, size/M, lgtm

#159 Update tekton tasks manifests to version v0.9.3
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M, approved

#167 Update tekton tasks manifests to version v0.10.0
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-data-object/manifests/create-data-object.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm
