Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2022-10, with the labels that each got.

#194 Update tekton tasks manifests to version v0.12.0
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-data-object/manifests/modify-data-object.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M, approved

#198 update golang version to 1.18 in github actions
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm

#197 Update tekton tasks manifests to version v0.12.1
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-data-object/manifests/modify-data-object.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M, approved

#201 Add 0xFelix to approvers
  OWNERS
Labels: dco-signoff: yes, size/XS, lgtm
