Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2022-04, with the labels that each got.

#116 update golang version in github actions
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/XS, lgtm

#117 Update tekton tasks manifests to version v0.6.0
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M

#119 add step to GH actions to upload released manifests to TTO
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/M, lgtm

#118 Add deleteDatavolumeTemplate parameter to modify-vm-template task
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  modules/modify-vm-template/pkg/templates/template-provider.go
  modules/modify-vm-template/pkg/utils/parse/clioptions.go
  modules/modify-vm-template/pkg/utils/parse/clioptions_test.go
  modules/sharedtest/testobjects/template/rhel-tiny.go
  modules/tests/test/constants/modify-vm-template.go
  modules/tests/test/modify-vm-template_test.go
  modules/tests/test/testconfigs/modify-vm-template-test-config.go
  modules/tests/vendor/github.com/kubevirt/kubevirt-tekton-tasks/modules/sharedtest/testobjects/template/rhel-tiny.go
  tasks/modify-vm-template/README.md
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  templates/modify-vm-template/manifests/modify-vm-template.yaml
Labels: dco-signoff: yes, size/XL, lgtm

#120 Update tekton tasks manifests to version v0.7.0
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M

#122 bump quay.io/kubevirt/libguestfs-tools image to v0.52.0
  modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
  modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
Labels: dco-signoff: yes, size/XS, lgtm

#124 add datavolumeTemplates parameter to modify-vm-template task
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  modules/modify-vm-template/pkg/templates/template-provider.go
  modules/modify-vm-template/pkg/utils/parse/clioptions.go
  modules/modify-vm-template/pkg/utils/parse/clioptions_test.go
  modules/tests/test/constants/modify-vm-template.go
  modules/tests/test/modify-vm-template_test.go
  modules/tests/test/testconfigs/modify-vm-template-test-config.go
  tasks/modify-vm-template/README.md
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  templates/modify-vm-template/manifests/modify-vm-template.yaml
Labels: dco-signoff: yes, size/L, lgtm

#123 Add missing defaults to modify-vm-template manifest
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  modules/tests/test/modify-vm-template_test.go
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  templates/modify-vm-template/manifests/modify-vm-template.yaml
Labels: dco-signoff: yes, size/M, lgtm

#125 Fix typo in modify-vm-template test
  modules/tests/test/modify-vm-template_test.go
Labels: dco-signoff: yes, size/XS, lgtm

#127 add param allowReplace in copy template task
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  modules/copy-template/pkg/templates/template-provider.go
  modules/copy-template/pkg/utils/parse/clioptions.go
  modules/copy-template/pkg/utils/parse/clioptions_test.go
  modules/tests/test/constants/copy-template.go
  modules/tests/test/copy_template_test.go
  modules/tests/test/testconfigs/copy-template-config.go
  tasks/copy-template/README.md
  tasks/copy-template/manifests/copy-template.yaml
  templates/copy-template/manifests/copy-template-role.yaml
  templates/copy-template/manifests/copy-template.yaml
Labels: dco-signoff: yes, size/L, lgtm

#128 add new parameters to modify template task
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  modules/modify-vm-template/pkg/templates/template-provider.go
  modules/modify-vm-template/pkg/utils/parse/clioptions.go
  modules/modify-vm-template/pkg/utils/parse/clioptions_test.go
  modules/tests/test/constants/modify-vm-template.go
  modules/tests/test/create_vm_common_test.go
  modules/tests/test/modify-vm-template_test.go
  modules/tests/test/testconfigs/modify-vm-template-test-config.go
  tasks/modify-vm-template/README.md
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  templates/modify-vm-template/manifests/modify-vm-template.yaml
Labels: dco-signoff: yes, size/L, lgtm

#130 Update tekton tasks manifests to version v0.8.0
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M
