Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2022-07, with the labels that each got.

#171 wait for tekton to be deployed
  automation/e2e-deploy-resources.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm

#172 wait for tekton pipelines webhook
  automation/e2e-deploy-resources.sh
Labels: dco-signoff: yes, size/S, approved, lgtm

#173 Update docs of example pipelines
  examples/pipelines/windows10-customize/README.md
  examples/pipelines/windows10-installer/README.md
Labels: dco-signoff: yes, size/S, approved, lgtm

#179 Change serviceAccountNames that is deprecated in pipelineRun examples
  examples/pipelines/server-deployer/server-deployer-pipelinerun.yaml
  examples/pipelines/unit-tester/unit-tester-pipelinerun.yaml
  examples/pipelines/virt-sysprep-updater/virt-sysprep-updater-pipelinerun.yaml
  examples/pipelines/windows10-customize/windows10-customize-pipelinerun-kubernetes.yaml
  examples/pipelines/windows10-customize/windows10-customize-pipelinerun-okd.yaml
  examples/pipelines/windows10-installer/windows10-installer-pipelinerun-kubernetes.yaml
  examples/pipelines/windows10-installer/windows10-installer-pipelinerun-okd.yaml
Labels: dco-signoff: yes, size/L, approved, lgtm

#177 add support for pipelineRuns in testing framework
  modules/tests/test/constants/timeout.go
  modules/tests/test/framework/framework.go
  modules/tests/test/pipelines_test.go
  modules/tests/test/runner/pipelinerunner.go
  modules/tests/test/tekton/pipelinerun.go
  modules/tests/test/tekton/utils.go
  modules/tests/test/testconfigs/pipeline-test-config.go
  modules/tests/test/testconfigs/test-config.go
Labels: dco-signoff: yes, size/L, approved, lgtm
