Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2022-08, with the labels that each got.

#176 add delete option to create-data-object task
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  modules/create-data-object/cmd/create-data-object/main.go
  modules/create-data-object/pkg/constants/constants.go
  modules/create-data-object/pkg/dataobject/provider.go
  modules/create-data-object/pkg/utils/parse/clioptions.go
  modules/tests/test/constants/create-data-object.go
  modules/tests/test/create_data_object_test.go
  modules/tests/test/framework/framework.go
  modules/tests/test/pipelines_test.go
  modules/tests/test/tekton/pipelinerun.go
  modules/tests/test/testconfigs/create-data-object-test-config.go
  tasks/create-data-object/README.md
  tasks/create-data-object/manifests/create-data-object.yaml
  templates/create-data-object/manifests/create-data-object.yaml
Labels: dco-signoff: yes, size/XL, approved, lgtm

#182 onboard modify-data-object task with basic files
  configs/modify-data-object.yaml
  configs/modify-object-task.yaml
  modules/modify-data-object/build/modify-data-object/Dockerfile
  scripts/common.sh
Labels: dco-signoff: yes, size/S, approved, lgtm

#184 bump golang version to 1.18.4
  modules/copy-template/build/copy-template/Dockerfile
  modules/create-vm/build/create-vm/Dockerfile
  modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
  modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
  modules/execute-in-vm/build/execute-in-vm/Dockerfile
  modules/generate-ssh-keys/build/generate-ssh-keys/Dockerfile
  modules/modify-data-object/build/modify-data-object/Dockerfile
  modules/modify-vm-template/build/modify-vm-template/Dockerfile
  modules/wait-for-vmi-status/build/wait-for-vmi-status/Dockerfile
Labels: dco-signoff: yes, size/S, approved, lgtm

#185 bump version of ubi images to 9
  modules/copy-template/build/copy-template/Dockerfile
  modules/create-vm/build/create-vm/Dockerfile
  modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
  modules/disk-virt-customize/build/disk-virt-customize/repos/CentOS-Stream-rhsrvany.repo
  modules/disk-virt-customize/build/disk-virt-customize/repos/CentOS-Stream.repo
  modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
  modules/disk-virt-sysprep/build/disk-virt-sysprep/repos/CentOS-Stream-rhsrvany.repo
  modules/disk-virt-sysprep/build/disk-virt-sysprep/repos/CentOS-Stream.repo
  modules/execute-in-vm/build/execute-in-vm/Dockerfile
  modules/generate-ssh-keys/build/generate-ssh-keys/Dockerfile
  modules/modify-data-object/build/modify-data-object/Dockerfile
  modules/modify-vm-template/build/modify-vm-template/Dockerfile
  modules/wait-for-vmi-status/build/wait-for-vmi-status/Dockerfile
Labels: dco-signoff: yes, size/L, approved

#183 remove create-data-object dockerfile
  modules/create-data-object/build/create-data-object/Dockerfile
Labels: dco-signoff: yes, size/XS, approved, lgtm

#186 Update tekton tasks manifests to version v0.11.0
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-data-object/manifests/modify-data-object.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M, approved

#188 bump libguestfs image to version v0.55
  modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
  modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
Labels: dco-signoff: yes, size/XS, approved

#189 disk-virt-[customize|sysprep]: Add more optional workspaces
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  templates/disk-virt-customize/manifests/disk-virt-customize.yaml
  templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
Labels: dco-signoff: yes, size/L, approved, lgtm
