Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2023-07, with the labels that each got.

#253 [release-v0.13] chore: debug wait-for-vmi and execute-in-vm tests
  automation/e2e-deploy-resources.sh
  modules/tests/test/disk_virt_libguestfs_tasks_test.go
  modules/tests/test/execute_and_cleanup_vm_test.go
  modules/tests/test/runner/taskrunrunner.go
  modules/tests/test/tekton/taskrun.go
  modules/tests/test/wait_for_vmi_status_test.go
Labels: dco-signoff: yes, size/L, approved

#255 chore: add more reviewers
  OWNERS
Labels: dco-signoff: yes, size/XS, approved, lgtm

#257 chore: update example pipelines documentation
  README.md
  examples/pipelines/windows-bios-installer/README.md
  examples/pipelines/windows-bios-installer/windows10-installer-pipelinerun-kubernetes.yaml
  examples/pipelines/windows-bios-installer/windows10-installer-pipelinerun-okd.yaml
  examples/pipelines/windows-bios-installer/windows10-installer-pipelinerun.yaml
  examples/pipelines/windows-customize/README.md
  examples/pipelines/windows-customize/windows10-customize-pipelinerun-kubernetes.yaml
  examples/pipelines/windows-customize/windows10-customize-pipelinerun-okd.yaml
  examples/pipelines/windows-customize/windows10-customize-pipelinerun.yaml
  examples/pipelines/windows-customize/windows11-customize-pipelinerun-okd.yaml
  examples/pipelines/windows-customize/windows11-customize-pipelinerun.yaml
  examples/pipelines/windows-customize/windows2k22-customize-pipelinerun-okd.yaml
  examples/pipelines/windows-customize/windows2k22-customize-pipelinerun.yaml
  examples/pipelines/windows-efi-installer/README.md
  examples/pipelines/windows-efi-installer/windows11-installer-pipelinerun-okd.yaml
  examples/pipelines/windows-efi-installer/windows11-installer-pipelinerun.yaml
  examples/pipelines/windows-efi-installer/windows2k22-installer-pipelinerun-okd.yaml
  examples/pipelines/windows-efi-installer/windows2k22-installer-pipelinerun.yaml
Labels: dco-signoff: yes, size/XL, approved, lgtm
