Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2023-11, with the labels that each got.

#278 [release-v0.16] chore: Bump google.golang.org/grpc
  modules/tests/go.mod
  modules/tests/go.sum
  modules/tests/vendor/github.com/golang/glog/glog.go
  modules/tests/vendor/github.com/golang/glog/glog_file.go
  modules/tests/vendor/github.com/golang/glog/glog_file_linux.go
  modules/tests/vendor/github.com/golang/glog/glog_file_other.go
  modules/tests/vendor/github.com/golang/glog/glog_file_posix.go
  modules/tests/vendor/github.com/golang/glog/glog_flags.go
  modules/tests/vendor/google.golang.org/grpc/README.md
  modules/tests/vendor/google.golang.org/grpc/attributes/attributes.go
  modules/tests/vendor/google.golang.org/grpc/balancer/balancer.go
  modules/tests/vendor/google.golang.org/grpc/clientconn.go
  modules/tests/vendor/google.golang.org/grpc/dialoptions.go
  modules/tests/vendor/google.golang.org/grpc/encoding/encoding.go
  modules/tests/vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  modules/tests/vendor/google.golang.org/grpc/internal/backoff/backoff.go
  modules/tests/vendor/google.golang.org/grpc/internal/internal.go
  modules/tests/vendor/google.golang.org/grpc/internal/status/status.go
  modules/tests/vendor/google.golang.org/grpc/internal/transport/handler_server.go
  modules/tests/vendor/google.golang.org/grpc/internal/transport/http2_client.go
  modules/tests/vendor/google.golang.org/grpc/internal/transport/http2_server.go
  modules/tests/vendor/google.golang.org/grpc/internal/transport/http_util.go
  modules/tests/vendor/google.golang.org/grpc/internal/transport/transport.go
  modules/tests/vendor/google.golang.org/grpc/server.go
  modules/tests/vendor/google.golang.org/grpc/tap/tap.go
  modules/tests/vendor/google.golang.org/grpc/version.go
  modules/tests/vendor/google.golang.org/grpc/vet.sh
  modules/tests/vendor/modules.txt
Labels: dco-signoff: yes, size/XL, approved

#277 chore: Bump google.golang.org/grpc
  modules/tests/go.mod
  modules/tests/go.sum
  modules/tests/vendor/github.com/golang/glog/glog.go
  modules/tests/vendor/github.com/golang/glog/glog_file.go
  modules/tests/vendor/github.com/golang/glog/glog_file_linux.go
  modules/tests/vendor/github.com/golang/glog/glog_file_other.go
  modules/tests/vendor/github.com/golang/glog/glog_file_posix.go
  modules/tests/vendor/github.com/golang/glog/glog_flags.go
  modules/tests/vendor/google.golang.org/grpc/README.md
  modules/tests/vendor/google.golang.org/grpc/attributes/attributes.go
  modules/tests/vendor/google.golang.org/grpc/balancer/balancer.go
  modules/tests/vendor/google.golang.org/grpc/clientconn.go
  modules/tests/vendor/google.golang.org/grpc/dialoptions.go
  modules/tests/vendor/google.golang.org/grpc/encoding/encoding.go
  modules/tests/vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  modules/tests/vendor/google.golang.org/grpc/internal/backoff/backoff.go
  modules/tests/vendor/google.golang.org/grpc/internal/internal.go
  modules/tests/vendor/google.golang.org/grpc/internal/status/status.go
  modules/tests/vendor/google.golang.org/grpc/internal/transport/handler_server.go
  modules/tests/vendor/google.golang.org/grpc/internal/transport/http2_client.go
  modules/tests/vendor/google.golang.org/grpc/internal/transport/http2_server.go
  modules/tests/vendor/google.golang.org/grpc/internal/transport/http_util.go
  modules/tests/vendor/google.golang.org/grpc/internal/transport/transport.go
  modules/tests/vendor/google.golang.org/grpc/server.go
  modules/tests/vendor/google.golang.org/grpc/tap/tap.go
  modules/tests/vendor/google.golang.org/grpc/version.go
  modules/tests/vendor/google.golang.org/grpc/vet.sh
  modules/tests/vendor/modules.txt
Labels: dco-signoff: yes, size/XL, approved

#286 [release-v0.12]feat: add .snyk file
  .snyk
Labels: dco-signoff: yes, size/S, approved, lgtm

#285 [release-v0.13]feat: add .snyk file
  .snyk
Labels: dco-signoff: yes, size/S, approved, lgtm

#284 [release-v0.15]feat: add .snyk file
  .snyk
Labels: dco-signoff: yes, size/S, approved, lgtm

#291 feat: configure dependabot
  .github/dependabot.yml
Labels: dco-signoff: yes, size/M, approved, lgtm
