Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2023-03, with the labels that each got.

#233 fix: increase emptyDir size in modify-windows-iso-file task to 12Gi
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
  templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
Labels: dco-signoff: yes, size/S, approved, lgtm

#235 Add deprecation annotations
  README.md
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  tasks/copy-template/README.md
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-template/README.md
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/modify-vm-template/README.md
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  templates/copy-template/manifests/copy-template.yaml
  templates/copy-template/readmes/README.md
  templates/create-vm-from-manifest/manifests/create-vm.yaml
  templates/create-vm-from-template/readmes/README.md
  templates/modify-vm-template/manifests/modify-vm-template.yaml
  templates/modify-vm-template/readmes/README.md
Labels: dco-signoff: yes, size/S, approved

#238 Update tekton tasks manifests to version v0.13.3
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-data-object/manifests/modify-data-object.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm
