Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2024-02, with the labels that each got.

#321 feat: simplify test-yaml-consistency script
  .github/workflows/test-yaml-consistency.yaml
  scripts/test-yaml-consistency.sh
Labels: dco-signoff: yes, size/M, approved, lgtm

#322 feat: update to Go 1.21
  .github/workflows/release.yaml
  automation/generatetasks/build/Dockerfile
  build/Containerfile
  build/Containerfile.DiskVirt
  modules/copy-template/go.mod
  modules/copy-template/vendor/modules.txt
  modules/create-vm/go.mod
  modules/create-vm/go.sum
  modules/create-vm/vendor/modules.txt
  modules/disk-virt-customize/go.mod
  modules/disk-virt-customize/go.sum
  modules/disk-virt-customize/vendor/modules.txt
  modules/disk-virt-sysprep/go.mod
  modules/disk-virt-sysprep/go.sum
  modules/disk-virt-sysprep/vendor/modules.txt
  modules/execute-in-vm/go.mod
  modules/execute-in-vm/vendor/modules.txt
  modules/generate-ssh-keys/go.mod
  modules/generate-ssh-keys/go.sum
  modules/generate-ssh-keys/vendor/modules.txt
  modules/modify-data-object/go.mod
  modules/modify-data-object/go.sum
  modules/modify-data-object/vendor/modules.txt
  modules/modify-vm-template/go.mod
  modules/modify-vm-template/go.sum
  modules/modify-vm-template/vendor/modules.txt
  modules/shared/go.mod
  modules/shared/go.sum
  modules/shared/vendor/modules.txt
  modules/sharedtest/go.mod
  modules/tests/go.mod
  modules/tests/go.sum
  modules/tests/vendor/modules.txt
  modules/wait-for-vmi-status/go.mod
  modules/wait-for-vmi-status/vendor/modules.txt
Labels: dco-signoff: yes, size/L, approved, lgtm

#323 feat: preparation for onboarding tasks to artifact hub
  .github/workflows/artifact-hub-linter.yaml
  .github/workflows/release.yaml
  .gitignore
  configs/cleanup-vm.yaml
  configs/copy-template.yaml
  configs/create-vm-from-manifest.yaml
  configs/create-vm-from-template.yaml
  configs/disk-virt-customize.yaml
  configs/disk-virt-sysprep.yaml
  configs/execute-in-vm.yaml
  configs/generate-ssh-keys.yaml
  configs/modify-data-object.yaml
  configs/modify-object-task.yaml
  configs/modify-vm-template.yaml
  configs/modify-windows-iso-file.yaml
  configs/wait-for-vmi-status.yaml
  makefile
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/copy-released-manifests.sh
  scripts/run-ah-linter.sh
  tasks/cleanup-vm/cleanup-vm.yaml
  tasks/copy-template/copy-template.yaml
  tasks/create-vm-from-manifest/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/create-vm-from-template.yaml
  tasks/disk-virt-customize/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/disk-virt-sysprep.yaml
  tasks/execute-in-vm/execute-in-vm.yaml
  tasks/generate-ssh-keys/generate-ssh-keys.yaml
  tasks/modify-data-object/modify-data-object.yaml
  tasks/modify-vm-template/modify-vm-template.yaml
  tasks/modify-windows-iso-file/modify-windows-iso-file.yaml
  tasks/wait-for-vmi-status/wait-for-vmi-status.yaml
  templates/copy-template/manifests/copy-template.yaml
  templates/create-vm-from-manifest/manifests/create-vm.yaml
  templates/disk-virt-customize/manifests/disk-virt-customize.yaml
  templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  templates/execute-in-vm/manifests/execute-in-vm.yaml
  templates/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  templates/modify-data-object/manifests/modify-data-object.yaml
  templates/modify-vm-template/manifests/modify-vm-template.yaml
  templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
  templates/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/XL, approved, lgtm

#324 feat: add artifact hub annotations
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  tasks/cleanup-vm/cleanup-vm.yaml
  tasks/copy-template/copy-template.yaml
  tasks/create-vm-from-manifest/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/create-vm-from-template.yaml
  tasks/disk-virt-customize/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/disk-virt-sysprep.yaml
  tasks/execute-in-vm/execute-in-vm.yaml
  tasks/generate-ssh-keys/generate-ssh-keys.yaml
  tasks/modify-data-object/modify-data-object.yaml
  tasks/modify-vm-template/modify-vm-template.yaml
  tasks/modify-windows-iso-file/modify-windows-iso-file.yaml
  tasks/wait-for-vmi-status/wait-for-vmi-status.yaml
  templates/copy-template/manifests/copy-template.yaml
  templates/create-vm-from-manifest/manifests/create-vm.yaml
  templates/disk-virt-customize/manifests/disk-virt-customize.yaml
  templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  templates/execute-in-vm/manifests/execute-in-vm.yaml
  templates/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  templates/modify-data-object/manifests/modify-data-object.yaml
  templates/modify-vm-template/manifests/modify-vm-template.yaml
  templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
  templates/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/L, approved, lgtm

#328 feat: update libguestfs container to v1.1.1
  build/Containerfile.DiskVirt
Labels: dco-signoff: yes, size/XS, approved, lgtm

#326 feat: disable PRs to ssp operator during release
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm

#329 fix: remove test private ssh keys from manifests
  release/tasks/cleanup-vm/0.18.0/examples/secrets/ssh-secret-advanced.yaml
  release/tasks/cleanup-vm/0.18.0/examples/secrets/ssh-secret.yaml
  release/tasks/execute-in-vm/0.18.0/examples/secrets/ssh-secret-advanced.yaml
  release/tasks/execute-in-vm/0.18.0/examples/secrets/ssh-secret.yaml
  tasks/cleanup-vm/examples/secrets/ssh-secret-advanced.yaml
  tasks/cleanup-vm/examples/secrets/ssh-secret.yaml
  tasks/execute-in-vm/examples/secrets/ssh-secret-advanced.yaml
  tasks/execute-in-vm/examples/secrets/ssh-secret.yaml
  templates/execute-in-vm/examples/ssh-secret.yaml
Labels: dco-signoff: yes, size/L, approved, lgtm

#331 fix: tekton version in templates and tasks
  tasks/cleanup-vm/examples/taskruns/cleanup-vm-simple-taskrun.yaml
  tasks/cleanup-vm/examples/taskruns/cleanup-vm-with-ssh-taskrun.yaml
  tasks/copy-template/examples/taskruns/copy-template-taskrun.yaml
  tasks/create-vm-from-manifest/examples/taskruns/create-vm-from-manifest-taskrun.yaml
  tasks/create-vm-from-template/examples/taskruns/create-vm-from-template-taskrun.yaml
  tasks/disk-virt-customize/examples/taskruns/disk-virt-customize-taskrun-workspace.yaml
  tasks/disk-virt-customize/examples/taskruns/disk-virt-customize-taskrun.yaml
  tasks/disk-virt-sysprep/examples/taskruns/disk-virt-sysprep-taskrun-workspace.yaml
  tasks/disk-virt-sysprep/examples/taskruns/disk-virt-sysprep-taskrun.yaml
  tasks/execute-in-vm/examples/taskruns/execute-in-vm-with-ssh-taskrun.yaml
  tasks/generate-ssh-keys/examples/taskruns/generate-ssh-keys-advanced-taskrun.yaml
  tasks/generate-ssh-keys/examples/taskruns/generate-ssh-keys-simple-taskrun.yaml
  tasks/modify-data-object/examples/taskruns/modify-data-object-taskrun.yaml
  tasks/modify-vm-template/examples/taskruns/modify-vm-template-taskrun.yaml
  tasks/modify-windows-iso-file/examples/taskruns/modify-windows-iso-file-taskrun.yaml
  tasks/wait-for-vmi-status/examples/taskruns/wait-for-vmi-status-taskrun.yaml
  templates/cleanup-vm/examples/cleanup-vm-taskrun.yaml
  templates/copy-template/examples/copy-template-taskrun.yaml
  templates/create-vm-from-manifest/examples/create-vm-from-manifest-taskrun.yaml
  templates/create-vm-from-template/examples/create-vm-from-template-taskrun.yaml
  templates/disk-virt-customize/examples/disk-virt-customize-taskrun-workspace.yaml
  templates/disk-virt-customize/examples/disk-virt-customize-taskrun.yaml
  templates/disk-virt-sysprep/examples/disk-virt-sysprep-taskrun-workspace.yaml
  templates/disk-virt-sysprep/examples/disk-virt-sysprep-taskrun.yaml
  templates/execute-in-vm/examples/execute-in-vm-taskrun.yaml
  templates/generate-ssh-keys/examples/generate-ssh-keys-taskrun.yaml
  templates/modify-data-object/examples/modify-data-object-taskrun.yaml
  templates/modify-vm-template/examples/modify-vm-template-taskrun.yaml
  templates/modify-windows-iso-file/examples/modify-windows-iso-file-taskrun.yaml
  templates/wait-for-vmi-status/examples/wait-for-vmi-status-taskrun.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm

#327 feat: unify of okd and k8s tasks
  .github/workflows/release.yaml
  README.md
  configs/copy-template.yaml
  configs/create-vm-from-template.yaml
  configs/modify-vm-template.yaml
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/kubevirt-tekton-tasks.yaml
  scripts/generate-yaml-tasks.sh
  scripts/onboard-new-task-with-ci-stub.sh
Labels: dco-signoff: yes, size/XL, approved, lgtm

#333 fix: Remove use of kubevirt.io/v1alpha3 in example pipelines
  examples/pipelines/server-deployer/server-deployer-pipeline.yaml
  examples/pipelines/virt-sysprep-updater/virt-sysprep-updater-pipeline.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm

#334 fix: replacing of images in deploy-task.sh script
  scripts/deploy-tasks.sh
Labels: dco-signoff: yes, size/S, approved, lgtm

#335 chore: replace hardcoded annotations in templates with variables
  scripts/ansible/branding.yaml
  templates/cleanup-vm/generate-task.yaml
  templates/copy-template/generate-task.yaml
  templates/copy-template/manifests/copy-template.yaml
  templates/create-vm-from-manifest/generate-task.yaml
  templates/create-vm-from-manifest/manifests/create-vm.yaml
  templates/create-vm-from-template/generate-task.yaml
  templates/disk-virt-customize/generate-task.yaml
  templates/disk-virt-customize/manifests/disk-virt-customize.yaml
  templates/disk-virt-sysprep/generate-task.yaml
  templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  templates/execute-in-vm/generate-task.yaml
  templates/execute-in-vm/manifests/execute-in-vm.yaml
  templates/generate-ssh-keys/generate-task.yaml
  templates/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  templates/modify-data-object/generate-task.yaml
  templates/modify-data-object/manifests/modify-data-object.yaml
  templates/modify-vm-template/generate-task.yaml
  templates/modify-vm-template/manifests/modify-vm-template.yaml
  templates/modify-windows-iso-file/generate-task.yaml
  templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
  templates/wait-for-vmi-status/generate-task.yaml
  templates/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/L, approved, lgtm

#336 chore: update fedora version in CI image
  automation/generatetasks/build/Dockerfile
Labels: dco-signoff: yes, size/XS, approved, lgtm
