Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2024-04, with the labels that each got.

#359 chore: add link to example configmaps for pipelines to README of each
  release/pipelines/windows-bios-installer/README.md
  release/pipelines/windows-customize/README.md
  release/pipelines/windows-efi-installer/README.md
  templates-pipelines/windows-bios-installer/README.md
  templates-pipelines/windows-customize/README.md
  templates-pipelines/windows-efi-installer/README.md
Labels: dco-signoff: yes, size/XS, approved, lgtm

#360 chore: remove namespace params from pipelines
  automation/e2e-pipelines/test-files/windows10-customize-pipelinerun.yaml
  automation/e2e-pipelines/test-files/windows10-installer-pipelinerun.yaml
  automation/e2e-pipelines/test-files/windows11-customize-pipelinerun.yaml
  automation/e2e-pipelines/test-files/windows2k22-customize-pipelinerun.yaml
  automation/e2e-pipelines/test-files/windows2k22-installer-pipelinerun.yaml
  release/pipelines/windows-bios-installer/README.md
  release/pipelines/windows-bios-installer/windows-bios-installer.yaml
  release/pipelines/windows-customize/README.md
  release/pipelines/windows-customize/windows-customize.yaml
  release/pipelines/windows-efi-installer/README.md
  release/pipelines/windows-efi-installer/windows-efi-installer.yaml
  templates-pipelines/windows-bios-installer/README.md
  templates-pipelines/windows-bios-installer/manifests/windows-bios-installer.yaml
  templates-pipelines/windows-customize/README.md
  templates-pipelines/windows-customize/manifests/windows-customize.yaml
  templates-pipelines/windows-efi-installer/README.md
  templates-pipelines/windows-efi-installer/manifests/windows-efi-installer.yaml
Labels: dco-signoff: yes, size/L, approved, lgtm

#362 fix: readme of windows efi installer pipeline
  release/pipelines/windows-efi-installer/README.md
  templates-pipelines/windows-efi-installer/README.md
Labels: dco-signoff: yes, size/S, approved, lgtm

#363 chore: add variables for requirement in pipeline readmes
  release/pipelines/windows-bios-installer/README.md
  release/pipelines/windows-customize/README.md
  release/pipelines/windows-efi-installer/README.md
  scripts/ansible/branding.yaml
  templates-pipelines/windows-bios-installer/README.md
  templates-pipelines/windows-customize/README.md
  templates-pipelines/windows-efi-installer/README.md
Labels: dco-signoff: yes, size/S, approved, lgtm

#365 chore: bump ginkgo package
  .github/dependabot.yml
  automation/build-test.sh
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/flags.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/M, approved, lgtm

#368 chore: improve logs in modify-data-object
  modules/modify-data-object/pkg/dataobject/provider.go
Labels: dco-signoff: yes, size/XS, approved, lgtm

#379 Fix: Broken Link Fixes in main Readme.md (tasks/ -> release/tasks/)
  README.md
Labels: dco-signoff: yes, size/S, approved, lgtm, ok-to-test

#387 chore: disable AcceptEula tag in autounattend.xml ConfigMaps
  release/pipelines/windows-bios-installer/README.md
  release/pipelines/windows-bios-installer/configmaps/windows-bios-installer-configmaps.yaml
  release/pipelines/windows-efi-installer/README.md
  release/pipelines/windows-efi-installer/configmaps/windows-efi-installer-configmaps.yaml
  scripts/deploy-pipelines.sh
  templates-pipelines/windows-bios-installer/README.md
  templates-pipelines/windows-bios-installer/configmaps/windows-bios-installer-configmaps.yaml
  templates-pipelines/windows-efi-installer/README.md
  templates-pipelines/windows-efi-installer/configmaps/windows-efi-installer-configmaps.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm

#383 chore: download bootsources from quay instead of dockerhub
  modules/sharedtest/testobjects/alpine-vm.go
  modules/sharedtest/testobjects/fedora-cloud-vm.go
  modules/sharedtest/testobjects/template/cirros-tiny.go
  test/disk_virt_libguestfs_tasks_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm
