Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2024-01, with the labels that each got.

#302 Update tekton tasks manifests to version v0.17.0
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  scripts/makefile-snippets/makefile-release.mk
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-data-object/manifests/modify-data-object.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm

#305 fix: race condition when allowReplace is true in modify-data-object task
  modules/modify-data-object/pkg/dataobject/provider.go
Labels: dco-signoff: yes, size/M, approved, lgtm

#314 feat: bump api version of task to v1 in manifests
  manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  manifests/okd/kubevirt-tekton-tasks-okd.yaml
  tasks/cleanup-vm/manifests/cleanup-vm.yaml
  tasks/copy-template/manifests/copy-template.yaml
  tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
  tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
  tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
  tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  tasks/execute-in-vm/manifests/execute-in-vm.yaml
  tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  tasks/modify-data-object/manifests/modify-data-object.yaml
  tasks/modify-vm-template/manifests/modify-vm-template.yaml
  tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
  tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
  templates/copy-template/manifests/copy-template.yaml
  templates/create-vm-from-manifest/manifests/create-vm.yaml
  templates/disk-virt-customize/manifests/disk-virt-customize.yaml
  templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
  templates/execute-in-vm/manifests/execute-in-vm.yaml
  templates/generate-ssh-keys/manifests/generate-ssh-keys.yaml
  templates/modify-data-object/manifests/modify-data-object.yaml
  templates/modify-vm-template/manifests/modify-vm-template.yaml
  templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
  templates/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Labels: dco-signoff: yes, size/L, approved, lgtm

#316 feat: configure dependabot
  .github/dependabot.yml
Labels: dco-signoff: yes, size/M, approved, lgtm

#318 Remove 'codingben' from OWNERS
  OWNERS
Labels: dco-signoff: yes, size/XS, approved, lgtm
