Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2024-11, with the labels that each got.

#548 feat: add timeout parameter to modify-data-object task
  modules/modify-data-object/pkg/dataobject/provider.go
  modules/modify-data-object/pkg/utils/parse/clioptions.go
  modules/modify-data-object/pkg/utils/parse/clioptions_test.go
  release/tasks/modify-data-object/README.md
  release/tasks/modify-data-object/modify-data-object.yaml
  templates/modify-data-object/manifests/modify-data-object.yaml
Labels: dco-signoff: yes, release-note, size/M, approved, lgtm

#543 feat(CNV-40411): set default instancetype and preference labels
  cmd/disk-uploader/main.go
  modules/disk-uploader/pkg/image/image.go
  modules/disk-uploader/pkg/vmexport/vmexport.go
  modules/disk-uploader/pkg/vmexport/vmexport_test.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/fake/clientset_generated.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/fake/doc.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/fake/register.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/doc.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_cdi.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_cdiconfig.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_core_client.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_dataimportcron.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_datasource.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_datavolume.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_objecttransfer.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_storageprofile.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_volumeclonesource.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_volumeimportsource.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_volumeuploadsource.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/upload/v1beta1/fake/doc.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/upload/v1beta1/fake/fake_upload_client.go
  vendor/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/upload/v1beta1/fake/fake_uploadtokenrequest.go
  vendor/modules.txt
Labels: size/XXL, dco-signoff: yes, release-note, approved, lgtm

#552 feat: enable VMPersistentState feature gate in kubevirt
  automation/e2e-deploy-resources.sh
Labels: dco-signoff: yes, size/XS, release-note-none, approved, lgtm

#550 feat: remove deployment of instance types in e2e tests
  automation/e2e-deploy-resources.sh
Labels: dco-signoff: yes, size/XS, release-note-none, approved, lgtm

#562 fix(CNV-40411): add new disk-uploader roles
  examples/pipelines/disk-uploader/disk-uploader-role.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, approved, lgtm
