Repository kubevirt/kubevirt-tekton-tasks, pull requests merged in 2025-01, with the labels that each got.

#575 fix(CNV-53189): make PUSH_TIMEOUT an optional param
  release/tasks/disk-uploader/README.md
  release/tasks/disk-uploader/disk-uploader.yaml
  release/tasks/disk-uploader/examples/taskruns/disk-uploader-taskrun-resolver.yaml
  templates/disk-uploader/examples/disk-uploader-taskrun.yaml
  templates/disk-uploader/manifests/disk-uploader.yaml
Labels: dco-signoff: yes, size/XS, release-note, approved, lgtm

#592 [release-v0.15] Cherry pick 498 to release v0.15
  automation/e2e-deploy-resources.sh
  modules/tests/test/create_vm_from_template_test.go
  modules/tests/test/test_suite_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, approved

#574 fix(CNV-53190): use emptyDir to store downloaded disk
  release/tasks/disk-uploader/disk-uploader.yaml
  templates/disk-uploader/manifests/disk-uploader.yaml
Labels: dco-signoff: yes, release-note, size/S, approved, lgtm

#576 docs(CNV-53188): improve disk-uploader usage guidance
  configs/disk-uploader.yaml
  examples/pipelines/disk-uploader/disk-uploader-pipelinerun.yaml
  release/tasks/disk-uploader/README.md
  release/tasks/disk-uploader/disk-uploader.yaml
  release/tasks/disk-uploader/examples/taskruns/disk-uploader-secret.yaml
  release/tasks/disk-uploader/examples/taskruns/disk-uploader-taskrun-resolver.yaml
  templates/disk-uploader/examples/disk-uploader-taskrun.yaml
  templates/disk-uploader/generate-task.yaml
  templates/disk-uploader/manifests/disk-uploader.yaml
  templates/disk-uploader/readmes/README.md
Labels: dco-signoff: yes, size/M, release-note-none, approved, lgtm

#595 feat: disable renovate's regular dependency updates
  renovate.json
Labels: dco-signoff: yes, size/XS, release-note-none, approved, lgtm

#599 feat: do not panic inside code
  cmd/create-vm/main.go
  cmd/disk-uploader/main.go
  cmd/disk-virt-customize/main.go
  cmd/disk-virt-sysprep/main.go
  cmd/execute-in-vm/main.go
  cmd/generate-ssh-keys/main.go
  cmd/modify-data-object/main.go
  cmd/wait-for-vmi-status/main.go
  modules/disk-virt/pkg/execute/executor.go
  modules/execute-in-vm/pkg/cmd/cmd.go
  modules/execute-in-vm/pkg/cmd/cmd_test.go
  modules/generate-ssh-keys/pkg/generate/generate-ssh-keys.go
  modules/shared/pkg/exit/exit.go
  modules/shared/pkg/exit/exit_suite_test.go
  modules/shared/pkg/exit/exit_test.go
  modules/shared/pkg/utilstest/utils.go
  modules/shared/pkg/zerrors/multi-error.go
  modules/shared/pkg/zerrors/multi_error_test.go
  test/create_vm_from_manifest_test.go
  test/execute_and_cleanup_vm_test.go
Labels: dco-signoff: yes, release-note-none, size/XL, approved, lgtm

#604 chore: update versions from v0.23.0 to v0.24.0
  release/pipelines/windows-customize/README.md
  release/pipelines/windows-customize/pipelineruns/pipelineruns.yaml
  release/pipelines/windows-customize/windows-customize.yaml
  release/pipelines/windows-efi-installer/README.md
  release/pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml
  release/pipelines/windows-efi-installer/windows-efi-installer.yaml
  release/tasks/cleanup-vm/README.md
  release/tasks/cleanup-vm/cleanup-vm.yaml
  release/tasks/cleanup-vm/examples/taskruns/cleanup-vm-taskrun-resolver.yaml
  release/tasks/create-vm-from-manifest/README.md
  release/tasks/create-vm-from-manifest/create-vm-from-manifest.yaml
  release/tasks/create-vm-from-manifest/examples/taskruns/create-vm-from-manifest-taskrun-resolver.yaml
  release/tasks/disk-uploader/README.md
  release/tasks/disk-uploader/disk-uploader.yaml
  release/tasks/disk-uploader/examples/taskruns/disk-uploader-taskrun-resolver.yaml
  release/tasks/disk-virt-customize/README.md
  release/tasks/disk-virt-customize/disk-virt-customize.yaml
  release/tasks/disk-virt-customize/examples/taskruns/disk-virt-customize-taskrun-resolver.yaml
  release/tasks/disk-virt-sysprep/README.md
  release/tasks/disk-virt-sysprep/disk-virt-sysprep.yaml
  release/tasks/disk-virt-sysprep/examples/taskruns/disk-virt-sysprep-taskrun-resolver.yaml
  release/tasks/execute-in-vm/README.md
  release/tasks/execute-in-vm/examples/taskruns/execute-in-vm-with-ssh-taskrun-resolver.yaml
  release/tasks/execute-in-vm/execute-in-vm.yaml
  release/tasks/generate-ssh-keys/README.md
  release/tasks/generate-ssh-keys/examples/taskruns/generate-ssh-keys-advanced-taskrun-resolver.yaml
  release/tasks/generate-ssh-keys/generate-ssh-keys.yaml
  release/tasks/modify-data-object/README.md
  release/tasks/modify-data-object/examples/taskruns/modify-data-object-taskrun-resolver.yaml
  release/tasks/modify-data-object/modify-data-object.yaml
  release/tasks/modify-windows-iso-file/README.md
  release/tasks/modify-windows-iso-file/examples/taskruns/modify-windows-iso-file-taskrun-resolver.yaml
  release/tasks/modify-windows-iso-file/modify-windows-iso-file.yaml
  release/tasks/wait-for-vmi-status/README.md
  release/tasks/wait-for-vmi-status/examples/taskruns/wait-for-vmi-status-taskrun-resolver.yaml
  release/tasks/wait-for-vmi-status/wait-for-vmi-status.yaml
  scripts/makefile-snippets/makefile-release.mk
Labels: dco-signoff: yes, release-note, size/L, approved, lgtm

#597 fix(CNV-54663): show status of used export sources
  cmd/disk-uploader/main.go
  modules/disk-uploader/pkg/vmexport/vmexport.go
Labels: dco-signoff: yes, release-note, size/S, approved, lgtm

#614 feat: do not exit with error when tekton result folder does not exists in disk-uploader
  cmd/disk-uploader/main.go
  modules/shared/pkg/results/results.go
Labels: dco-signoff: yes, release-note, size/S, approved, lgtm
